#!/usr/bin/python3
serverParams=open('config/ssh.json','r').read()
gitParams=open('config/git.json','r').read()
hostingServer=input('Server host: ')
serverParams=serverParams.replace('<hostname>',hostingServer)
hostingLogin=input('Server login: ')
serverParams=serverParams.replace('<username>',hostingLogin)
hostingPath=input('Site path on server: ')
serverParams=serverParams.replace('<remotepath>',hostingPath)
gitAddr=input('Connection string to private git repo: ')
gitParams=gitParams.replace('<addrgitrepo>',gitAddr)
open('config/ssh.json', 'w').write(serverParams)
open('config/git.json','w').write(gitParams)